media:
  input: public
  output: /

content:
  - name: pages
    label: Pages
    type: collection
    path: src/content/pages
    fields:
      - { name: title, label: Title, type: string }
      - { name: slug, label: Slug, type: slugify }
      - { name: description, label: SEO Description, type: string }
      - name: sections
        label: Page Sections
        type: block
        list:
          collapsible:
            collapsed: true
            summary: "{type} section ({index})"
        blockKey: type
        blocks:
          - name: hero
            label: Hero Section
            fields:
              - name: content
                type: variantConditional
                variantLabel: Hero Type
                defaultVariant: typeOne
                variants:
                  typeOne:
                    label: Hero Type One
                    fields:
                      - { name: heading, label: Heading, type: string }
                      - { name: description, label: Description, type: text }
                      - name: buttons
                        label: Buttons
                        type: list
                        fields:
                          - { name: label, type: string }
                          - { name: url, type: string }
                      - { name: image, label: Image URL, type: string }
                  typeTwo:
                    label: Hero Type Two
                    fields:
                      - { name: title, label: Title, type: string }
                      - { name: subtitle, label: Subtitle, type: text }
                      - { name: phone, label: Phone, type: string }
                      - name: services
                        label: Services List
                        type: list
                        fields:
                          - { name: label, type: string }
                      - { name: bgImage, label: Background Image URL, type: string }

          - name: text
            label: Text Block
            fields:
              - { name: content, label: Content, type: rich-text }

          - name: features
            label: Features Section
            fields:
              - { name: title, label: Title, type: string }
              - name: items
                label: Feature Items
                type: list
                collapsible:
                  collapsed: true
                  summary: "{title} ({index})"
                fields:
                  - { name: icon, type: string }
                  - { name: title, type: string }
                  - { name: description, type: text }

          - name: testimonials
            label: Testimonial Section
            fields:
              - { name: title, type: string }
              - name: testimonialsRef
                label: Select Testimonials
                type: reference
                list: true

          - name: cta
            label: Call To Action
            fields:
              - { name: heading, type: string }
              - { name: buttonText, type: string }
              - { name: buttonLink, type: string }
