media:
  input: public
  output: /

content:
  - name: pages
    label: Pages
    type: collection
    path: src/content/pages
    fields:
      - { name: title, label: Title, type: string }
      - { name: slug, label: Slug, type: string }
      - { name: description, label: SEO Description, type: string }
      - name: sections
        label: Page Sections
        type: block
        list:
          collapsible:
            collapsed: true
            summary: "{type} section ({index})"
        blockKey: type
        blocks:
          - name: hero-two-columns
            label: Hero Two Columns
            fields:
              - { name: heading, label: Heading, type: string }
              - { name: descruption, label: Description, type: string }
              - name: buttons
                label: Buttons
                fields:
                  - { name: label, type: string }
                  - { name: url, type: string }
                list: true
              - { name: image, label: Image URL, type: image }

          - name: hero-with-quote
            label: Hero with Quote
            fields:
              - { name: title, label: Title, type: string }
              - { name: subtitle, label: Subtitle, type: text }
              - { name: phone, label: Phone, type: string }
              - name: buttons
                label: Buttons
                fields:
                  - { name: label, type: string }
                  - { name: url, type: string }
                list: true
              - { name: bgImage, label: Background Image URL, type: image }

          - name: single-hero
            label: Single Hero
            fields:
              - { name: title, label: Title, type: string }
              - { name: description, label: Description, type: string }
              - { name: bgImage, label: Background Image URL, type: image }

          - name: testimonial-twocol
            label: Testimonial Two Column
            fields:
              - { name: heading, label: Heading, type: string }
              - { name: description, label: Description, type: string }
              - { name: image, label: Image URL, type: image }


          - name: testimonial-slider
            label: Testimonial Slider
            fields:
              - { name: heading, label: Heading, type: string }
              - { name: subheading, label: Subheading, type: string }

          - name: about-us
            label: About Us
            fields:
              - { name: title, label: Title, type: string }
              - { name: description, label: Description, type: string }
              - name: features
                label: Features
                list: true
                fields:
                  - { name: icon, type: image }
                  - { name: title, type: string }
                  - { name: text, type: string }
              - { name: image, label: Image URL, type: image }

          - name: our-work-process
            label: Our Work Process
            fields:
              - { name: heading, label: Heading, type: string }
              - { name: description, label: Description, type: string }
              - name: cards
                label: Cards
                list: true
                fields:
                  - { name: icon, type: image }
                  - { name: title, type: string }

          - name: services
            label: Services
            fields:
              - { name: heading, label: Heading, type: string }
              - { name: description, label: Description, type: string }
          - name: cta-banner
            label: Call to Action Banner
            fields:
              - { name: title, label: Title, type: string }
              - { name: description, label: Description, type: string }
              - { name: buttonText, label: Button Text, type: string }
              - { name: buttonUrl, label: Button URL, type: string }
              - { name: bgColor, label: Background Color, type: color }
              - { name: textColor, label: Text Color, type: color }
